/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import main.Shop;
import model.Amount;

/**
 *
 * @author admin
 */
public class ShopView extends javax.swing.JFrame {
    Shop shop;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShopView.class.getName());

    /**
     * Creates new form ShopView
     */
    public ShopView() {
        this.shop = new Shop();

        shop.loadInventory();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contarCaja = new javax.swing.JButton();
        addProduct = new javax.swing.JButton();
        addStock = new javax.swing.JButton();
        deleteProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contarCaja.setBackground(new java.awt.Color(204, 255, 255));
        contarCaja.setText("1. Contar Caja");
        contarCaja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contarCaja.addActionListener(this::contarCajaActionPerformed);

        addProduct.setBackground(new java.awt.Color(204, 255, 255));
        addProduct.setText("2. Añadir productos");
        addProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addProduct.addActionListener(this::addProductActionPerformed);

        addStock.setBackground(new java.awt.Color(204, 255, 255));
        addStock.setText("3. Añadir stock");
        addStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addStock.addActionListener(this::addStockActionPerformed);

        deleteProduct.setBackground(new java.awt.Color(204, 255, 255));
        deleteProduct.setText("9. Eliminar producto");
        deleteProduct.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteProduct.addActionListener(this::deleteProductActionPerformed);

        jLabel1.setText("Seleccione o pulse una opción: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contarCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contarCaja)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteProduct)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contarCajaActionPerformed
        // TODO add your handling code here:
        openCashView();

    }//GEN-LAST:event_contarCajaActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
        int add = 2;
        openProductView(add);
    }//GEN-LAST:event_addProductActionPerformed

    private void addStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStockActionPerformed
        // TODO add your handling code here:
        int update = 3;
        openProductView(update);
    }//GEN-LAST:event_addStockActionPerformed

    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductActionPerformed
        // TODO add your handling code here:
        int delete = 9;
        openProductView(delete);
    }//GEN-LAST:event_deleteProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShopView().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton addStock;
    private javax.swing.JButton contarCaja;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void openCashView() {
        System.out.println("cash");
        CashView cashv = new CashView(this, true, shop);
        cashv.setLocationRelativeTo(null);
        cashv.setVisible(true);
    }

    private void openProductView(int option) {
        System.out.println("product");
        ProductView2 productv = new ProductView2(this, true, shop, option);
        productv.setLocationRelativeTo(null);
        productv.setVisible(true);
        
    }
    
    
}
